<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-KI9J8S8" failures="3" tests="3" name="Test(failed)" time="0.576" errors="0" timestamp="2023-01-13T23:25:43 IST">
  <testcase classname="org.TestNGEx3.ReportsEx3" name="DeleteCustomer" time="0.108">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at org.TestNGEx3.ReportsEx3.DeleteCustomer(ReportsEx3.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- DeleteCustomer -->
  <testcase classname="org.testNGEx4.ReportsEx2" name="CustomerUpdate" time="0.006">
    <failure type="java.lang.StringIndexOutOfBoundsException" message="String index out of range: 7">
      <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: 7
at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
at java.base/java.lang.String.charAt(String.java:1515)
at org.testNGEx4.ReportsEx2.CustomerUpdate(ReportsEx2.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CustomerUpdate -->
  <testcase classname="org.testNGEx4.ReportsEx2" name="CustomerCreate" time="0.005">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="Index 5 out of bounds for length 4">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 4
at org.testNGEx4.ReportsEx2.CustomerCreate(ReportsEx2.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- CustomerCreate -->
  <testcase classname="org.TestNGEx3.ReportsEx3" name="deleteCustomer" time="0.0">
    <ignored/>
  </testcase> <!-- deleteCustomer -->
  <testcase classname="org.testNGEx4.ReportsEx2" name="customerCreate" time="0.0">
    <ignored/>
  </testcase> <!-- customerCreate -->
</testsuite> <!-- Test(failed) -->
